# Site settings
title: CSS Structure
email: brad@azpixels.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bradwestfall.github.io/css-structure" # the base hostname & protocol for your site
#twitter_username: phxjavascript

# Build settings
#markdown: kramdown
markdown: redcarpet
highlighter: pygments

# GitHub Flavored Markdown
#kramdown:
#  input: GFM